default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spotcode_development

test:
  <<: *default
  database: spotcode_test

production:
  <<: *default
  database: spotcode_production
  username: spotcode
  password: <%= ENV['SPOTCODE_DATABASE_PASSWORD'] %>
